### PR TITLE
Use admesh's stl_repair() instead of simulating it ourselves.

### LINKED ISSUE #4805: Slic3r crashs loading STL
**Describe the bug**
I need to print the gears of this package: https://www.thingiverse.com/thing:974906
When I load the STL file, Slic3r crashes. This is the output:
```
$ slic3r
realloc(): invalid next size
Aborted (core dumped)
```
I also tried to fix the .stl file with `slic3r --repair` but it doesn't work too.

**To Reproduce**
1. Go to 'https://www.thingiverse.com/thing:974906'
2. Download and unzip files
3. Open _gears.stl_

**3D Model and Slic3r Configuration Export**
[issue.zip](https://github.com/slic3r/Slic3r/files/3167614/issue.zip)

**Expected behavior**
Open STL file

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Version 1.3.0 (installed by [AUR](https://aur.archlinux.org/packages/slic3r/))

### PR DESCRIPTION
**Pull request by lordofhyphens**
fixes #4805

### CODE REVIEW

**Comment by lordofhyphens** [comment]
Also probably avoids/patches #3317

File: xs/src/libslic3r/TriangleMesh.cpp [hunk 1]
```diff
@@ -172,23 +172,9 @@ TriangleMesh::repair() {
...
-    }
-    
-    // normal_directions
-    stl_fix_normal_directions(&stl);
-    
-    // normal_values
-    stl_fix_normal_values(&stl);
+
+    /// Call the stl_repair from admesh rather than reimplementing it ourselves.
+    stl_repair(&(this->stl), 1, 1, 0, 0, 0, 0, 0, 100, 1, 1, 1, 1, 1, 0);
```
Comment (hroncok) [inline xs/src/libslic3r/TriangleMesh.cpp]: The long list of arguments is very hard to read (yes, the API is not good), maybe add comment that explains the nonzero values?

Comment (lordofhyphens) [reply xs/src/libslic3r/TriangleMesh.cpp]: Good idea. Fixed.
